### ISSUE TITLE
Add a Background portal implementation 

### ISSUE THREAD

**Issue by mikix** [linuxmint/xdg-desktop-portal-xapp#2]
Some apps use this to autostart and run in the background, and/or provide information about running background tasks.

See Gnome’s version here: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/background.c

Two apps that I know use this are Deja Dup Backups and Pika Backup. Without this portal, those apps can’t provide scheduled backup support. I’m sure there are other examples, but that’s one at least.

**Comment by moshhh** [comment]
Seconding this request. I use pikabackup as my primary backup tool and not having the automatic backups here is a bit annoying.

**Comment by taltamir** [comment]
Crow translate also has problems (cannot change settings).

**Comment by taltamir** [comment]
I was under the impression that the reason pika backup does not work is because mint uses an older version of the flatpack portal.
As per discussion here
https://github.com/flatpak/xdg-desktop-portal/issues/1014

xdg-desktop-portal is an important component of flatpak. specifically it is the desktop integration portal for Flatpak
It is developed by flatpak developers in the flathub github.
https://github.com/flatpak/xdg-desktop-portal

If you check ubuntu
[https://packages.ubuntu.com/search?keyw ... top-portal](https://packages.ubuntu.com/search?keywords=xdg-desktop-portal)
jammy (22.04LTS) is running v1.14
kinetic (22.10) is running v1.15
lunar (23.04) is running v1.16

Mint is based on jammy LTS or debian LTS which both use v1.14

Pika Backup allegedly (according to discussing at first link I posted) requires v1.16.
Hypothetically, I think it should be possible to install an older version of pika backup, Deja Dup, or crow translate and those older versions should work on mint.

Or import and install the v1.16 of xdg-desktop-portal from ubuntu lunar.
currently version on mint is specifically "1.14 ubuntu" which suggests that mint did not modify this package from ubuntu jammy

**Comment by taltamir** [comment]
I believe Crow Translate is another program that needs it. as per
https://github.com/crow-translate/crow-translate/issues/599

**Comment by debilin** [comment]
+1 :pray:

**Comment by carobinario** [comment]
I can confirm this issue still exists on Linux Mint 21.3 Cinnamon. Please fix it, thanks.

ps. I can't schedule Pika Backup backups.

**Comment by guryushika** [comment]
I have the same error on Mint 21.3, fresh install. I’ve tried to tinker around in Flatseal and in different places add org.freedesktop.portal.Background (don’t really understand exactly what it is). Same error message.

**Comment by lumper5** [comment]
Issue remains unresolved nearly 1 yr later. Still no pika possible on LM with "default" flatpak. Pika works perfectly on Pop! OS, though. Maybe I should just give up and move all my desktops to Pop.

**Comment by AtomicRobotMan0101** [comment]
see https://github.com/linuxmint/xdg-desktop-portal-xapp

**Comment by mtwebster** [comment]
This should be in the next version, working on it.

**Comment by Magnusretrotech** [comment]
Will this be fixed for linux mint 22?

**Comment by mtwebster** [comment]
Yes, it is already fixed and will be part of Mint 22:
4be1618e39f8afe32a1419e0ad9b5588594bf500

**Comment by 1fexd** [comment]
Can confirm that PikaBackup can now start scheduled backups automatically, but from what I can tell, this portal implementation does not provide access to secrets, right (PikaBackup fails to read the encryption password from the system keyring)?

**Comment by mtwebster** [comment]
No secret support at the moment - it doesn't look like it's implemented in gnome yet either. It doesn't look too involved, I could definitely get to it for the next release.

Would you mind opening a new issue for this?

Also, if you can, please provide some steps test this in an actual app. There's a 'Door Knocker' app that only checks if the various portals are being advertised, but it doesn't see if they actually work.  There's a newer app 'ASHPD Demo' that tests functionality also, but it's still better to have a 'practical' test case.

Thanks

**Comment by 1fexd** [comment]
> Would you mind opening a new issue for this?

https://github.com/linuxmint/xdg-desktop-portal-xapp/issues/19
